jamming_power: '-45'
jamming_type: cw3
receiver_name: GP01
seed: 42
output_dir: PARSED_PROCESSED/GP01/cw3/-45/seed_42

prepare_data:
  train_val_ratio: 0.80
  val_split_ratio: 0.10
  window_size: 10
  stride: 10

train:
  accelerator: cuda
  devices: 1
  hidden_dim: 256
  initial_lr: 0.001
  weight_decay_val: 0.01
  n_epochs: 100
  model_name: JaGuard
  output_dir: PARSED_REPORTS/GP01/cw3/-45/seed_42
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 10
    min_delta: 0.001
    verbose: true